apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spodial-hr-frontend.fullname" . }}
  labels:
    {{- include "spodial-hr-frontend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spodial-hr-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spodial-hr-frontend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        - name: {{ include "spodial-hr-frontend.fullname" . }}-pull-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ include "spodial-hr-frontend.fullname" . }}-envs              