apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spodial-hr-frontend.fullname" . }}-pull-secret
  labels:
    {{- include "spodial-hr-frontend.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "spodial-hr-frontend.imagePullSecret" .Values.image }}